image:
  file: .gitpod.Dockerfile
tasks:
  - command: 'bash scripts/installSFDXAndAutorizeDevhub.sh'
vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.14:YDCg1YnVJIMuZM40rzK8PA==
    - chuckjonas.apex-pmd@0.5.3:6tkJLus49Nj2xG0DjHTYug==
    - salesforce.salesforcedx-vscode-core@51.3.0:jN1YWc6JpjkKDJdeWeJDig==
    - salesforce.salesforcedx-vscode-apex@51.3.0:8G5K8Tg/jUOmd+9xW5ksTA==
    - salesforce.salesforcedx-vscode-apex-debugger@51.3.0:hpUpbTqgeKzsF3ZPFEWOIA==
    - salesforce.salesforcedx-vscode-visualforce@51.3.0:EXDFwLo7STpwoeesQyQUMg==
    - salesforce.salesforcedx-vscode-lightning@51.3.0:fdSn9WvdUNNKKrVvjFplBQ==
    - salesforce.salesforcedx-vscode-apex-replay-debugger@51.3.0:4kpWb/glvjuQVih9eFmtlA==
    - salesforce.salesforce-vscode-slds@1.4.2:RBeVAaJc5y2TS6at+hksTQ==
    - salesforce.salesforcedx-vscode-lwc@51.3.0:0BT/sKl3OkyOfcPtEYVgAw==