language: java
script: 
- git submodule add --force https://github.com/florianhoehn/GIT-CI.git 
- ant -lib GIT-CI/lib/ -f GIT-CI/build.xml validate -v
notifications:
  slack: mavenschat:2Pmhpn10xoK1ZfvHfV648YHe