os: linux
sudo: required
language: node_js
node_js: 12

branches:
  only: 
  - master

stages:
  - name: Execute Static Code Analysis
  - name: Create Org
  - name: Push
  - name: Run Tests
  - name: Delete Scratch Org

jobs:
  include:
  - stage: Execute Static Code Analysis
    name: Run pmd
    install:
      - wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.16.0/pmd-bin-6.16.0.zip
      - unzip -o pmd-bin-6.16.0.zip
    script:
      - ./pmd-bin-6.16.0/bin/run.sh pmd -d src/main/default/classes -R ruleset.xml -f textcolor
      - ./pmd-bin-6.16.0/bin/run.sh pmd -d src/main/default/classes/tests -R ruleset.xml -f textcolor
      - ./pmd-bin-6.16.0/bin/run.sh pmd -d src/main/default/classes/example -R ruleset.xml -f textcolor
      - ./pmd-bin-6.16.0/bin/run.sh pmd -d src/main/default/classes/example/tests -R ruleset.xml -f textcolor

  - stage: Create Org
    name: Create Scratch Org
    install: bash scripts/installSFDXAndAutorizeDevhub.sh
    script: sfdx force:org:create --definitionfile config/project-scratch-def.json --setalias CI --setdefaultusername --durationdays 1 --targetdevhubusername DEVHUB

  - stage: Push
    name: Push Metadata
    install: bash scripts/installSFDXAndAutorizeDevhub.sh
    script: sfdx force:source:push --forceoverwrite --loglevel fatal --wait 30 --targetusername CI

  - stage: Run Tests
    name: Run Unit Tests
    install: bash scripts/installSFDXAndAutorizeDevhub.sh
    script: sfdx force:apex:test:run --targetusername CI --testlevel RunLocalTests --codecoverage --resultformat human

  - stage: Delete Scratch Org
    name: Delete Scratch Org
    install: bash scripts/installSFDXAndAutorizeDevhub.sh
    script: bash scripts/dx/deleteScratchOrg.sh CI