sudo: required
language: java
branches:
  only:
    - master
env:
  - GOPATH=$HOME/go PATH=$GOPATH/bin:$PATH
before_script:
  - npm install -g codeclimate-test-reporter
  - export SFDX_AUTOUPDATE_DISABLE=true
  - export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
  - export SFDX_DOMAIN_RETRY=300
  - wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJf -
  - "./sfdx/install"
  - export PATH=./sfdx/$(pwd):$PATH
  - sfdx update
  - echo -e $CI_HUB > server.key
  - sfdx force:auth:jwt:grant --clientid $CI_CLIENTID --jwtkeyfile server.key --username $CI_USERNAME --setdefaultdevhubusername -a HubOrg

script:
  - sfdx force:org:create -v HubOrg -s -f ./config/project-scratch-def.json -a CIorg
  - sfdx force:source:push -u CIorg
  - sfdx force:apex:test:run -u CIorg -c -r human
  - sfdx force:org:delete -u CIorg -p